databases:
  - name: GestionnaireDonnéesOGSLdb
    plan: free
    databaseName: GestionnaireDonnéesOGSLdb
    user: admin

services:
  - type: web
    plan: free
    name: GestionnaireDonnéesOGSL
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn GestionnaireDonnéesOGSL.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: GestionnaireDonnéesOGSLdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4